server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer-register?
    password: 'postgres'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: none
      show-sql: 'true'
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
