server:
  port: 8080

spring:
  application:
    name: customer
  liquibase:
    change-log: classpath:db/master.xml
  datasource:
    username: 'root'
    url: jdbc:postgresql://localhost:5433/customer?
    password: 'root'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: none
      show-sql: 'true'
    driver-class-name: org.postgresql.Driver


  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
