server:
  port: 8082

spring:
  application:
    name: notification

  datasource:
    username: 'postgres'
    password: 'postgres'
    url: jdbc:postgresql://localhost:5432/notification
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: create
      show-sql: 'true'

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
